apiVersion: v2
name: libreconnector
description: Umbrella chart for the LibreConnector and supporting components
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  # Contains control-plane and integrated data-planes
  #  - and other supported plugins as needed.
  # DID Web Host is a good way to ensure participant-agents registered with 
  # this control-plane can access the 
  # Only HTTP data-plane - access-token flow will be supported for now
  # Also an API for a UI to eventually use

  - name: libreconnector
    version: "0.0.1-local"
    repository: file://dependency_charts/libreconnector
  - name: mongodb
    version: "13.15.4"
    repository: https://charts.bitnami.com/bitnami
  # We need an OpenIDConnect and OAuth system for 
  # the purpose of supporting interactions - Keycloak or Ory Kratos/Hydra or Dex with OpenLDAP?
  # At least one of these must support the OIDC4CI and OIDC4VP flow
  # Not sure if the flow is agnostic of implementation or not.

  # We need an associated SSI wallet with the connector to handle interactions 
  # for the credentials being issued and storing the DID documents
  # Also for generating presentations as needed.
  
  # We need a third-party implementation that may do (zero-knowledge) analytics?

  # Distributed tracing with Zipkin or similar